### ISSUE TITLE
I wish to contribute

### ISSUE THREAD

**Issue by Lyraedan** [SheerSt/pokewilds#1]
If i read correctly I'm suppose to leave a issue here?

I am a 23 y/o programmer from the UK. I am fluent in Java, Javascript and C# been programming since 2009.

I'd like to ask if you'd like a Launcher / Updater created as i'd be more then happy to write that for you.

If there are any other things you'd need assistance with whether that be bug fixing, networking maybe even a login system
i'd me more then happy to assist.

I do have a couple projects that are public on my github as of right now. Most of mine are private but i'd be more then happy to show you some.

I'm in the discord server as ItsLuke#6703

**Comment by SheerSt** [comment]
Had an offline convo - closing.
