### ISSUE TITLE
Got owned by the Unown sign

### ISSUE THREAD

**Issue by qantuum** [SheerSt/pokewilds#101]
is it a bug or a feature?
will the garbled text go away eventually or do I have to take some action?

**Comment by Judosii** [comment]
I've found that triggering a random battle makes a unown appear, then the garbled text disappears until you check the sign again

**Comment by qantuum** [comment]
> I've found that triggering a random battle makes a unown appear, then the garbled text disappears until you check the sign again

ah, I see! thanks!

**Comment by fourlastor** [comment]
Closing as resolved
