### ISSUE TITLE
Couldn't load file: tiles/buildings/house5_middle1_E.png

### ISSUE THREAD

**Issue by 88Neaks** [SheerSt/pokewilds#104]
Good Evening!

Thank you for this wonderful game!

First of all, here's my .sav: [Dionysos.sav.zip](https://github.com/SheerSt/pokewilds/files/9229297/Dionysos.sav.zip)

I've been playing and enjoying the game a lot! However, I run into a problem... I was building a house, and when I entered it, my game froze. I tried to quit/save and rerun it, but from then, an Error Message popped out:

```
There was an error loading this file:


Couldn't load file: tiles/buildings/house5_middle1_E.png
com.badlogic.gdx.graphics.Pixmap,<init>(Pixmap.java:165)
com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
com.badlogic.gdx.graphics.Texture.<init>(Texture.java:122)
com.badlogic.gdx.graphics. Texture. <init>(T exture.java: 114)
com.pkmngen.game.util.TextureCache.get(TextureCache.java:142)
com.pkmngen.game.Tile.init(Tile.java:2314)
com.pkmngen.game.Tile.<init>(Tile.java:408)
com.pkmngen.game.Tile.get(T e.java:385)
com.pkmngen.game.PkmnMap.10adMapFromFile(PkmnMap.java:4897)
com.pkmngen.game.PkmnMap.loadFromFile(PkmnMap.java:5165)
com.pkmngen.game.DrawSetupMenu.step(Action.java:2468)
com.pkmngen.game.Game.render(Game.java:1400)
com.badlogic.gdx.backends.lwjgl.lwjglApplication.mainloop(lwjglApplication.java:232)
com.badlogic.gdx.backends.lwjgl.lwjglApplication$1.run(lwjglApplication.java:127)

Caused by: File not tound: tiles\buildings\house5_middle1_E.png (Internai)

com.badlogic.gdx.files.FileHandle.read(FileHandle.java:142)
com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:228)
com.badlogic.gdx.graphics.Pixmap,<init>(Pixmap.java:162)
com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
com.badlogic.gdx.graphics.Texture.<init>(Texture.java:122)
com.badlogic.gdx.graphics. Texture. <init>(T exture.java: 114)
com.pkmngen.game.util.TextureCache.get(TextureCache.java:142)
com.pkmngen.game.Tile.init(Tile.java:2314)
com.pkmngen.game.Tile,<init>(Tile.java:408)
com.pkmngen.game.Tile.get(Tile.java:385)
com.pkmngen.game.PkmnMap.loadMapFromFile(PkmnMap.java:4897)
com.pkmngen.game.PkmnMap.10adFromFile(PkmnMap.java:5165)
com.pkmngen.game.DrawSetupMenu.step(Action.java:2468)
com.pkmngen.game.Game.render(Game.j ava:1400)
com.badlogic.gdx.backends.lwjgl.lwjglApplication.mainl oop(LwjglApplication.java:232)
com.badlogic.gdx.backends.lwjgl.lwjglApplication$1.run(lwjglApplication.java:127)
com.pkmngen.game.DrawSetupMenu@537f1652
```

![Error](https://user-images.githubusercontent.com/110347147/182036300-15651aab-dcc3-4452-92c4-d350ab3f7c1b.png)

I know I can just use the .backup, but I've played and focused on building and capturing some specific Pokémon for a very long time today, I've done that to prepare for a journey. Coming back in time, losing all the work and progress i've done would probably kill my motivation :/

Do you have any idea how to fix this issue, please?

Thank you again for you help!

**Comment by SheerSt** [comment]
For anyone else having this issue, try this workaround:
 - make a `tiles` folder in the game's folder (in the same directory as the .jar)
 - make a `buildings` folder in the new `tiles` folder.
 - add this file to the buildings folder
![house_E](https://user-images.githubusercontent.com/8891626/182052197-2ed73908-290a-4f72-8b0c-5699b836443f.png)
 - Rename the .png file to whatever file the game is complaining about (ex: house5_middle1_E.png like in this issue)
