### ISSUE TITLE
[Question] How to spawn Regi dungeon

### ISSUE THREAD

**Issue by Faucheurdam** [SheerSt/pokewilds#124]
The Regi dungeon don't spawn at world generation.
Is there a puzzle to make it appear ?

**Comment by Lizardking13** [comment]
I think that in some versions it spawns on the other maps in the borders

**Comment by Faucheurdam** [comment]
I will look at that, thanks.

**Comment by Faucheurdam** [comment]
For the moment, i didn't see it.
