### ISSUE TITLE
Fixes with launcher

### ISSUE THREAD

**Issue by SlooowAndFurious** [SheerSt/pokewilds#135]
I've been installing the game both on Mac OS (for my girlfriend) and on linux (for me). I encountered some issues with the lauchers.
First, both of them need to have execution permissions.
```bash
chmod +x linux-launcher # on linux
chmod +x mac-launcher.command # on Mac OS
```

Second, I found 2 issues in the linux launcher. On line 3, the option used was `--version` which is only supported on later versions of Java. Yet, this game seems to work with Java 8 (not sure about that but it runs). For Java 8, we need `-version`. Then, on line 4, the jar file name doesn't match the jar file in the directory (`pokemon-wilds.jar` instead of `pokewilds.jar`).

I downloaded the `pokemon-wilds-otherplatforms.zip`.

**Comment by Orthus** [comment]
I'm gonna agree with this issue.

Here is a better bash script as it adds the game to the audio mixer:

#!/bin/bash
ALSOFT_DRIVERS=pulse
java -jar pokewilds.jar

**Comment by Draphon** [comment]
Could you perhaps help me figure out why I can get the game started?
![20220822_185512](https://user-images.githubusercontent.com/111829198/186089319-fc8b7760-b972-4549-b62b-cfd0f8783927.jpg)

**Comment by Orthus** [comment]
> Could you perhaps help me figure out why I can get the game started?

You can do one of two things
1. Right click the linux-launcher file > open with Kate change pokemon-wilds.jar to pokewilds.jar
2. Rename pokewilds.jar to pokemon-wilds.jar

**Comment by fourlastor** [comment]
@Orthus @SlooowAndFurious thank you for the suggestions! We recently released a [new version](https://github.com/SheerSt/pokewilds/releases/latest/) which includes a Linux executable in [AppImage](https://appimage.org/) format, this already includes java within and shouldn't have weird launcher problems anymore! :)
