### ISSUE TITLE
Level-up moves

### ISSUE THREAD

**Issue by Ryvinky** [SheerSt/pokewilds#136]
Often when reaching the level they should learn a move (according to documents posted here), pokemon will not learn the move. Several pokemon in my team became useless as they leveled up because they never learned stronger moves

**Comment by Timoris** [comment]
Duplicate of https://github.com/SheerSt/pokewilds/issues/121

**Comment by fourlastor** [comment]
Hi, this is because we still didn't implement all the moves, we're working on it :)

**Comment by Codz155** [comment]
@fourlastor pokemon don't learn Some Moves that already in the game like quick Attack on eevee at lvl 10 its supposed learn it but it does not . At lease for me

**Comment by fourlastor** [comment]
@Codz155 eevee learnset (the one present in the released game) follows the [generation 2 learnset](https://pokemondb.net/pokedex/eevee/moves/2)
