### ISSUE TITLE
Cant open game on steamdeck linux

### ISSUE THREAD

**Issue by Draphon** [SheerSt/pokewilds#137]
![20220822_185512](https://user-images.githubusercontent.com/111829198/186053984-decb1c06-96ff-44b6-90df-a6cf97805567.jpg)
This is the files downloaded and extracted to the folder what am I missing?

Thanks

**Comment by SheerSt** [comment]
> ![20220822_185512](https://user-images.githubusercontent.com/111829198/186053984-decb1c06-96ff-44b6-90df-a6cf97805567.jpg) This is the files downloaded and extracted to the folder what am I missing?
> 
> Thanks

@Draphon 

I don't own a steam deck, I have never personally tried running Wilds on one. In the past, people on the discord server have said that you can use Proton to run the windows version, maybe that would work for you.

**Comment by Draphon** [comment]
Using Proton ge was able to get windows version to run

**Comment by cobalt2727** [comment]
> This is the files downloaded and extracted to the folder what am I missing?
> 
> Thanks

What error message did you get when trying to run it?

**Comment by fourlastor** [comment]
@Draphon we recently released a [new version](https://github.com/SheerSt/pokewilds/releases/latest/) which should be much easier to run natively on Linux, could you try that out?

You should be able to run it by double clicking this executable, once you decompress the archive:

![image](https://user-images.githubusercontent.com/1263058/193359845-940ecafb-735c-4758-a111-680335cb72e8.png)

**Comment by fourlastor** [comment]
Got a steam deck and tested, the game runs on it :)
