### ISSUE TITLE
ATTACK field move can trigger a battle against an Egg

### ISSUE THREAD

**Issue by simjnd** [SheerSt/pokewilds#139]
Unsure if this is intentional or not, but using the ATTACK field move can trigger a battle against an egg.
Upon defeating the egg, the parents aren't upset like they are if you steal it.
The egg can't be caught during a battle (using balls isn't possible).
<img width="591" alt="image" src="https://user-images.githubusercontent.com/43272781/186661118-34049431-d017-4b42-bb93-07ac418d4b07.png">

**Comment by fourlastor** [comment]
@simjnd this is actually intentional, you can use the attack move to check for shinies without having to hatch the egg.
