### ISSUE TITLE
screen goes black when game loads

### ISSUE THREAD

**Issue by Zaymus** [SheerSt/pokewilds#140]
For a while after I load my save file, The world is black for minutes before it is goes back to normal, this issue happens multiple times. overlays still function along with controls and battles, just the movement and world interaction is nearly impossible.

Let me know if there are any debug or save files I can supply to help the diagnostic run faster

(Running on windows machine btw)

**Comment by andrec0sta** [comment]
Experiencing the same or similar bug. In my case, most of the times is when I enter a biome with shaders or when entering pokemon mansion

Windows 11

**Comment by Zaymus** [comment]
@andrec0sta, yea I did a little more experimenting and it does seem to trigger on biome load but also when it turns to night in the day/night cycle. I am also on windows 11, I tried on my desktop that is windows 10 and it seems to work perfectly

**Comment by fourlastor** [comment]
@andrec0sta @Zaymus we're aware of this bug, you should be able to work around by playing with two settings in the `settings.txt` file:

```
drawReflections=true
drawOverlays=true
```

Try changing either (or both) to `false`, and the black screen issue should disappear (`drawOverlays` is likely the cause)
