### ISSUE TITLE
Wont save my game

### ISSUE THREAD

**Issue by 60thChip** [SheerSt/pokewilds#146]
Hey there. I want to start off by saying I have no programming skills or really much technical skills in general, hense why it probably took me like 3 hours get the game running on my mac.

I have played the game a few times putting in hours of game time each run but I can never get the program to save my file (after hitting save in the menu). If I close the program and boot it back up, it will be in the load screen. However the problem is that when I shut down my mac and open the game after starting it up, the load file is gone and and I can only start a new game. This is frustrating because the last playthrough I had a great team and hours of work on a settlement with an awesomely generated world. 

I have looked through the other forums and saw some responses. I did make sure to open the zip file and copy the files into a new folder and delete the zip file itself. I also saw a response saying "he .sav directories should be in the same folder as the game's .exe." but I cant find any .exe let alone a .sav directory.
------
I downloaded "Mac, Linux, Windows 32-bit: " from the discord page. Its contents include:

linux-launcher
mac-launcher.command
-both of which wont let me open in terminal saying I dont have appropriate access privileges despite the GetInfo tab saying I have read/write privileges

mods folder
-contains characters (red), pokemon (gible and pikachu), and a README.txt

pokewilds.jar 
-which opens through java only after hitting the "open with" option

settings.txt
-when edited doesn't actually edit the ingame settings which im only now realizing is because its a txt file
------

edit: also sorry, no idea why some of the text is formatted bold and larger font when I submitted, just created a github account now to ask this question

**Comment by 60thChip** [comment]
also sorry, no idea why some of the text is formatted bold and larger font when I submitted, just created a github account now to ask this question

**Comment by SheerSt** [comment]
@60thChip if you want to DM me on the discord server I can help you there (i apologize if you DMd me yesterday, discord introduced a new 'message preview' feature and it turned off all of my notifications for DMs)

Here are the instructions for running on mac:
 - Requires Java to be installed: https://www.oracle.com/java/technologies/downloads/#jdk17-mac
 - Single-click on the pokemon-wilds-v084-otherplatforms4 folder, click on Finder on the top bar, then Services, then select New Terminal at Folder. 
 - Enter `java -jar pokewilds.jar` into the terminal and press enter.

**Comment by 60thChip** [comment]
Thank you! Starting it up through the new terminal folder worked! it created a save file folder and even after restarting my computer it was there!

**Comment by fourlastor** [comment]
Closing this as resolved
