### ISSUE TITLE
photosensitive mode + logic

### ISSUE THREAD

**Issue by SheerSt** [SheerSt/pokewilds#15]
As per conversation on merged PR #11:

SheerSt - 

Slight issue regarding the Flash animation. I've had users report in the past that very quickly flashing black and white colors is a problem, especially since the game can be fullscreened. This was the case with the Low Kick animation, my solution was to replace all of the flashing with a single inverse_colors effect. Let me know your thoughts on the best way to handle this. It might be nice to somewhere keep a backup of the 'accurate' animation, maybe?

Liminalia -

As for the flashing issue, I think it's possible to add some kind of "seizure-free mode" user setting, track flashing programmatically and disable it when change between inverse_colors and normal colors occurs too often, for example by saving the frame number when inverse_colors is called in LoadAndPlayAnimation class and deny turning it off until a certain amount of frames has passed.

Tracking this issue here. 'photosensitive mode' toggle needs added to settings.txt and code logic described above needs added.

**Comment by 1iminal** [comment]
I've implemented this in pending PR in private repo.
