### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kermit10111111** [SheerSt/pokewilds#155]
2022-09-06T11:50:02.8840252+01:00 Couldn't create window

com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:22)

i just want to play it looks amazeing.

**Comment by scoutantho** [comment]
Hey, can you tell me more ? 
your setup, OS, which version you downloaded when would that happen ? 

Thanks

**Comment by kermit10111111** [comment]
It's a old laptop but it's all I have so I understand it may be a hardware
issue, but I can run command and canqour zero hour, so I thought I could
this game,

I downloaded the all platform version from github and got this error so I
downloaded all 4, then seen that 2 of them was for Linux and deleted them,
I tried the other file and get the same error I then deleted everything
reset laptop and tried them one at a time and still get the same error.

And it happens after I double click the pokewild.exe file this is the 1st
screen I see.

Device specfications

Processor is
Intel(R) core(TM) Duo CPU   t6670 @ 2.20GHz 2.20GHz

Installed RAM 3.00GB
System type 64 bit

Windows specification

Edition Windows 10 HOME
Version  21H2
OS build 19044.1889

**Comment by scoutantho** [comment]
Thanks for your answer, 2 things i can see here ( without getting on code for now -> i will soon) 
i think it is either the resolution that doesn't fit your computer or you have not enough ram ( but that will be strange) 
i'll tell you more if i have more info the day i look into the code :)

**Comment by fourlastor** [comment]
@kermit10111111 could you try these instructions? 

How to start the game in compatibility mode (windows 10):
 - Open the folder containing pokemon-wilds.exe
 - Shift + right-click in the folder and select 'Open powershell window here'
 - Type cmd in the window and press enter.
 - Type `pokemon-wilds.exe angle_gles20` into the window and press enter.

**Comment by kermit10111111** [comment]
Sorry for the late reply, and thank you for been so quick with yours. I'm
afraid that did not work...I opened the powershell and it brought up what
looked like cmd prompt...I typed cmd hit enter, then typed what you sent, I
did it with a space and with out a space and it reply with

 (pokemon-wilds.exe is not reconized as a internal or external
command,operable program or batch file)

**Comment by fourlastor** [comment]
@kermit10111111 my bad, `pokewilds.exe angle_gles20`. the name of the exe file changed, so that's why the command failed

**Comment by kermit10111111** [comment]
it looked like it worked then the next page was a error with this

com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:22)

**Comment by fourlastor** [comment]
@kermit10111111 could you paste the whole message? It's missing the error part

**Comment by kermit10111111** [comment]
i deleted the error report and tried it again and this is everything in the
notepad error report in the pokewilds folder


2022-09-29T12:10:59.6023035+01:00 Couldn't create window

com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:22)
2022-09-29T12:10:42.8972358+01:00 Couldn't create window

com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:22)

**Comment by fourlastor** [comment]
@kermit10111111 this error usually indicates that your graphics card driver doesn't support something. You can try two things:

1. Try to update the graphics card drivers, they might be outdated. This is preferrable as the game (and your computer overall) will run better with updated drivers.
2. Follow the following instructions to run it in compatibility mode (this will run most of the times, but it might be slower):

## How to start the game in compatibility mode (Windows 7/10):
 - Open the folder containing pokewilds.exe
 - Shift + right-click in an empty space in the folder and select 'Open powershell window here' (this will be 'Open command window here' in Windows 7)
 - Type `cmd` in the window and press enter. (skip this in Windows 7)
 - Type `pokewilds.exe angle_gles20` into the window and press enter.

**Comment by kermit10111111** [comment]
You legend!!!! Thank you so so much :) it's working.

**Comment by fourlastor** [comment]
Nice! Closing as resolved
