### ISSUE TITLE
Stuck after using Cut on a cactus

### ISSUE THREAD

**Issue by TasteofPomegranate** [SheerSt/pokewilds#156]
I used cut on one of the vanishing cactus right as it shifted from night to day and the cacti despawned.

While the game itself isn't frozen (I can see overworld pokemon wandering around), I am stuck. I cannot move, bring up the menu, or stop using the field move.

**Comment by fourlastor** [comment]
@TasteofPomegranate if your game doesn't respond to input (there are a few cases we're aware of), for now you can close the game, which will prompt you to save if you haven't done so recently, respond yes to saving, and reload the game.
