### ISSUE TITLE
Battle music fails at night

### ISSUE THREAD

**Issue by dzamie** [SheerSt/pokewilds#16]
I can't figure out what circumstances cause this, but triggering a wild battle at night will often not play wild_battle_intro or wild_battle. Instead, the overworld night music continues to play throughout the battle. Victory music still works as intended, however.

**Comment by SheerSt** [comment]
Hi there. Battle music not playing at night is intended currently, it's just for the atmosphere. There has been discussion around changing the way night music works for v0.9, battle music may play at night in the future.

**Comment by fourlastor** [comment]
Closing this as outdated
