### ISSUE TITLE
X32 will be avilable for playing in old PC,s?

### ISSUE THREAD

**Issue by KNKOGAMING** [SheerSt/pokewilds#169]
Can i use pokemon wilds in a x32 computer¿?¿?¿?¿

**Comment by fourlastor** [comment]
@KNKOGAMING you can use the [otherplatforms](https://github.com/SheerSt/pokewilds/releases/latest/download/pokewilds-otherplatforms.zip) version to run the game on x32 computers:

 - Requires Java to be installed: https://www.oracle.com/java/technologies/downloads/#jdk17-windows
 - Double-click on pokewilds.jar to run.
