### ISSUE TITLE
PokeWilds crashed :( reasons:

### ISSUE THREAD

**Issue by Jergar05** [SheerSt/pokewilds#170]
D:\Jeremy's Stuff\Pokemon Wilds\pokemon-wilds-v84-windows4\error

2022-09-16T20:18:43.2683871+08:00 Couldn't create window

com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:22)

**Comment by fourlastor** [comment]
@Jergar05 could you try [these steps](https://github.com/SheerSt/pokewilds/issues/155#issuecomment-1262137965)? It should let you run the game
