### ISSUE TITLE
Gible learnset

### ISSUE THREAD

**Issue by ReddDog1** [SheerSt/pokewilds#173]
should learn bulldoze at lvl 18 as of gen 8 learnset

**Comment by fourlastor** [comment]
@ReddDog1 thank you for the report, the moveset is still incomplete but we are planning to expand it

Versions 0.8.x will receive only bugfixes though, new content will be added in upcoming versions

**Comment by green1314** [comment]
> @ReddDog1 thank you for the report, the moveset is still incomplete but we are planning to expand it
> 
> Versions 0.8.x will receive only bugfixes though, new content will be added in upcoming versions

fighting!
