### ISSUE TITLE
Can't open game window

### ISSUE THREAD

**Issue by dumbsterdives** [SheerSt/pokewilds#196]
[error.log](https://github.com/SheerSt/pokewilds/files/9895524/error.log)
I get this popup after a few seconds every time i try to start the game.

**Comment by fourlastor** [comment]
@dumbsterdives are you on windows? You should be able to run the game by double clicking `pokewilds-compat`

**Comment by dumbsterdives** [comment]
I swear I tried troubleshooting compatibility back wgen i first had this issue, but this time it worked.
