### ISSUE TITLE
Character sprite switched with pokemon

### ISSUE THREAD

**Issue by francisco-orejarena** [SheerSt/pokewilds#2]
Hey, I just wanted to help describe some bugs that I ran into!

This one occurred when there was a pokemon (Charmander) that was following me and I was dropping him off. I actually think it may have started a little bit sooner, but I wasn't really paying attention. Regardless, it seems that at some point, the pokemon sprite and the character sprite were switched at some point. Please let me know what other information you may need for this.

**Comment by SheerSt** [comment]
Hi there :) thank you for reporting the issue, that's very helpful. People have been more actively reporting bugs on the discord and it's been reported there before - but having it here is good too.

I'm working on v0.8 currently and I'm planning to fix the issue for that release. It is mainly triggered by having a Pokemon FOLLOW you and then dropping it. A temporary workaround is to save and reload the game (or pick up the same Pokemon and drop it again)

**Comment by SheerSt** [comment]
Fixed in v0.8 so closing.
