### ISSUE TITLE
Save Disappearing

### ISSUE THREAD

**Issue by ArtistAstronomy** [SheerSt/pokewilds#201]
![image](https://user-images.githubusercontent.com/117063136/198941110-0613a992-6a7f-4f5c-94ef-25873c130171.png)
First time playing the game, played for around an hour before saving and exiting. When I came back, a popup informed me that the save was lost and to ask for help. Tried to look for it myself, but couldn't find anything. The save file is still there with three files ("game" "map0,0" "spawnnull0,0") and a png (map0,0). Deleted it, tried again on a new world, same response. Deleted the entire game, unzipped the file again and tried to make a new save file, the same message pops up.

**Comment by KARASVCXA** [comment]
I'm having the same issue and I have not found any information on how to fix it unfortunately.

**Comment by fourlastor** [comment]
@ArtistAstronomy @KARASVCXA hi! sorry for the late reply. Right now, you should be able to play on mac by following the instructions in the readme (make sure you download the latest version of the game, just in case):

## Mac

1. Requires Java to be installed: https://www.oracle.com/java/technologies/downloads/#jdk17-mac
2. In Finder, select the folder containing this readme, and on the top bar, click on "Finder", then "Services", then select "New Terminal at Folder".
3. Enter the following commands in the terminal:
```
cat mac-launcher.template > mac-launcher.command
chmod +x mac-launcher.command
```
Play the game by double-clicking `mac-launcher.command`.

You will need to do this setup only once
