### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kousnowflakes** [SheerSt/pokewilds#216]
The game for me is actually pretty good, though, I have a suggestion.
Can you add a music and sound effect adjuster in the game? I know the music is good and a bop at certain moments, but sometimes it's too loud for me and I wish I would turn it down a little bit. Thank you for reading my concerns, it's a really great mod and I'm enjoying it!

**Comment by fourlastor** [comment]
@Kousnowflakes this is planned and I agree, it's not optimal yet.

For the moment you should be able to at least mute the music by editing the `settings.txt` file and changing

``` 
muteMusic=false
```

to

```
muteMusic=true
```

Make sure not to put any extra spaces before/after the equal sign!
