### ISSUE TITLE
Path to Mewtwo Blocked

### ISSUE THREAD

**Issue by Raidbreak** [SheerSt/pokewilds#219]
![image](https://user-images.githubusercontent.com/117364385/199725741-b15b04a6-1e71-4b03-96ef-f19cf9064eb6.png)
I just can't acess mewtwo, tried to use rock smash on the boulders but it didn't work, is there a way to acess these stairs

**Comment by BKNadir** [comment]
![image](https://user-images.githubusercontent.com/19260941/199797187-9fd38fb3-716e-40c4-900c-5cc549915434.png)
try disable this door by interacting with a button on a statue

**Comment by Raidbreak** [comment]
Thank you so much, i can close this issue :D
