### ISSUE TITLE
game is extremely laggy

### ISSUE THREAD

**Issue by Senptistex** [SheerSt/pokewilds#224]
the game is so lagy its unplayable
in my task manager the game doesn't take much power at all
![image](https://user-images.githubusercontent.com/117378138/199771255-03613392-3315-4b50-87a4-fc76de4b5f85.png)
my pc is not hot garbage either its decent 
so i really don't know what's causing it

**Comment by svaughtAA** [comment]
@Senptistex I might be getting the same thing. With the 64-bit windows version. For me, it is only laggy when I have it on full screen. Everything is slowed down except for the music && sound effects. Is this the same for you?

**Comment by Senptistex** [comment]
@svaughtAA kinda yeah, 
but for me even not fullscreen is laggy as hell, 
not as laggy as fullscreen but still unplayable

**Comment by Senptistex** [comment]
@svaughtAA found the problem, it was my graphics card being old and poopy
if you have any option on your graphics card try putting them on optimal, it might help :)

**Comment by fourlastor** [comment]
@Senptistex glad to hear you found a solution! Unfortunately the game is still not as optimised as it could be, we're working on improving things every release (it's still very much in the early stages of development), so with older hardware it might be a bit tricky to run it
