### ISSUE TITLE
Stuck on Mountain

### ISSUE THREAD

**Issue by Lakoah** [SheerSt/pokewilds#229]
![Screenshot (17)](https://user-images.githubusercontent.com/117322154/199861622-11f693e5-fa4c-451e-ad14-ee542c439dc0.png)

I got here riding a Pokemon. I cannot get down.

**Comment by DJSwamp** [comment]
Use your escape rope in key items, it teleports you to the nearest shore. Also how did you get there riding a pokemon but can't get down?

**Comment by Lakoah** [comment]
I did use my escape rope, so it was okay. 
And I have no idea why I couldn't get down. It felt random, which is also why I took a screen shot. I went up on Ponyta, got stuck, I got off Ponyta, no luck, then I tried riding Onix. No luck. And tried them all again.

**Comment by Lakoah** [comment]
The website I found was pokemon log. So I was playing an old version. Cam be closed.
