### ISSUE TITLE
unable to open application (error file attached)

### ISSUE THREAD

**Issue by CrimsonCapricorn188** [SheerSt/pokewilds#231]
[error.log](https://github.com/SheerSt/pokewilds/files/9934437/error.log)

I also tried opening the .jar file, same thing.

**Comment by Lakoah** [comment]
Where did you download it from? Link?

**Comment by fourlastor** [comment]
@CrimsonCapricorn188 could you try downloading the latest version and using the `pokewilds-compat` launcher? (assuming you're on Windows)

**Comment by CrimsonCapricorn188** [comment]
@fourlastor Running pokewilds-compat did get it to open, but also gave me a message that the save data is trying to be sent to system32.

**Comment by fourlastor** [comment]
@CrimsonCapricorn188 are you running it from the search bar? that is known to give issues

**Comment by CrimsonCapricorn188** [comment]
@fourlastor Thanks, running it from desktop seems to have solved all current issues.
