### ISSUE TITLE
Not an issue but a question about unown

### ISSUE THREAD

**Issue by CaSe2474** [SheerSt/pokewilds#239]
Why is it that when you read a trainer tips sign (which is in unown alphabet), your next random encounter is unown? Also, why ARE the trainer tips in the unown alphabet?

**Comment by TheKennyGee** [comment]
It's an easter egg. After your unown encounter the signs should go back to normal.

**Comment by fourlastor** [comment]
> Why is it that when you read a trainer tips sign (which is in unown alphabet), your next random encounter is unown? Also, why ARE the trainer tips in the unown alphabet?

It's an in game event, capturing/defeating the unow will restore the normal text (also, unows are useful to farm rare candies)
