### ISSUE TITLE
Stuck Flying 

### ISSUE THREAD

**Issue by DarnellTorres** [SheerSt/pokewilds#241]
I managed to catch a Noctowl and use fly but I can't come down. The Noctowl's status is asleep, I think if this might be the reason for the bug as it is the only thing wrong. The game won't allow me to switch to ride another pokemon in my party and I am unable to make a pokemon follow me. Ive even tried dropping my Noctowl midflight and he still holds me hostage. Please send help :(

**Comment by TheKennyGee** [comment]
Have you tried holding X and descending? You can only do this if you're over solid ground (excluding roofs), unless you have a Pokemon that knows surf and you're over water.

**Comment by DarnellTorres** [comment]
omg!!! thank you! that totally worked :) I was confused because you're allowed to go from ride to fly so I assumed you'd be able to go from fly to ride as well.

**Comment by fourlastor** [comment]
@TheKennyGee thank you for helping out, I'll close this as resolved.
