### ISSUE TITLE
Impossible spawn

### ISSUE THREAD

**Issue by marijnjc88** [SheerSt/pokewilds#266]
I just created my first world, and got spawned on a small island with no way off.
![2022-11-08 (3)](https://user-images.githubusercontent.com/117781476/200687245-730ccf25-26de-440a-b0e5-3d56b1311c5f.png)
![2022-11-08 (4)](https://user-images.githubusercontent.com/117781476/200687252-4510bcfe-78a7-4eae-9df8-af8777b8dc8d.png)

**Comment by VibinAlot** [comment]
Yep, same here

**Comment by fourlastor** [comment]
@marijnjc88 @VibinAlot unfortunately this is a known bug that might happen from time to time, for now the only solution is to create another world
