### ISSUE TITLE
Hypnosis fails

### ISSUE THREAD

**Issue by CriminalPancake** [SheerSt/pokewilds#269]
A few times now I have tried hypnosis only for it to fail entirely. Both times it was against higher level pokemon so maybe that is the issue

**Comment by zackeroni9** [comment]
Not all moves have 100% accuracy, Hypnosis included.

**Comment by CriminalPancake** [comment]
Might be good to say that it missed then

**Comment by fourlastor** [comment]
The battle UI is being completely reworked for future versions (0.9 and onwards, no release date planned as of now) :sparkles: 

I'm closing the issue as 0.8 won't get any updates in the future (only bugfixes and performances improvements)
