### ISSUE TITLE
my map keeps on restarting after i re-load the game :/ pic of the error below

### ISSUE THREAD

**Issue by LeanMx** [SheerSt/pokewilds#274]
![312283817_1201971333997011_1912702781295734553_n](https://user-images.githubusercontent.com/117945900/201197981-cf6c7a0d-93ec-418a-87ef-37231829358e.png)

**Comment by fourlastor** [comment]
@LeanMx delete the file that it's failing to access (`map1,0.png`, make sure you delete the correct one), it's within your savegame folder (not the compressed archive).
Deleting it will reset your exploration of the map (the one visible through the minimap) but will solve the issue, this is a known bug so I'll close the issue, but feel free to open another one if you have more problems!
