### ISSUE TITLE
Invisible unmovable Pokemon

### ISSUE THREAD

**Issue by uraneaUmbra** [SheerSt/pokewilds#3]
I pressed enter immediately after putting my Krabby into my team, and while it was my team its sprite was also stuck midanimation where it stood. I went to put the Krabby somewhere else, and when I went back to the spot where it was it still functioned like it was there although it was invisible, I could get items and pick it up.
When I pick up the invisible Krabby, the version I placed earlier disappears, so it isn't an infinite Krabby generator. But I can't make the invisible one go away. I can dig and build in the spot, but that doesn't make it go away.

**Comment by SheerSt** [comment]
Hi there, thanks for reporting that. I'm currently working on Wilds v0.8 and I believe I have this issue fixed. Will close after I've had a chance to confirm.

**Comment by uraneaUmbra** [comment]
> Hi there, thanks for reporting that. I'm currently working on Wilds v0.8 and I believe I have this issue fixed. Will close after I've had a chance to confirm.

Awesome! Definitely not a big deal, I just want to report whatever I find. 
Is it better to post here or in the Discord?

**Comment by SheerSt** [comment]
>  Is it better to post here or in the Discord?

Either works fine :)

**Comment by SheerSt** [comment]
Fixed in v0.8 so closing.
