### ISSUE TITLE
Failed to launch JVM

### ISSUE THREAD

**Issue by MindeKing** [SheerSt/pokewilds#307]
Probably going to make a moron out of myself here, but

Windows 10
Downloaded and extracted the "pokemon-wilds-windows64.zip"
Tried running pokewilds.exe and pokewilds-compat.exe, but both display the same error message:
"Failed to launch JVM"
![image](https://user-images.githubusercontent.com/26449194/201826883-44da8e9d-b264-4091-95be-9ccdc030309c.png)
Installed the latest version of Java (1.8.0_351) just in case.
![image](https://user-images.githubusercontent.com/26449194/201827030-09dba4d0-829d-445c-8fd0-681b4d5005c6.png)
pokewilds.exe still displays the same error message.
Tried running the .jar from Explorer, but nothing happened.
Tried running the .jar from the command line to get more information,
![image](https://user-images.githubusercontent.com/26449194/201828202-9758dd84-fccf-4413-99a1-90b85a982d93.png)
but I have no idea what to do with it, or what any of it means.
I'm also hesitant to download seemingly random Java addons which haven't specifically been endorsed or required by PokeWilds itself
I've tried looking up what to do elsewhere, but to no avail.

Hopefully I'm just a moron and this is a quick fix.
Thank you for your time.

**Comment by vicmaple** [comment]
Try the 32-bit version of the game. Maybe that's the issue. 
https://github.com/SheerSt/pokewilds/releases/latest/download/pokewilds-otherplatforms.zip
(The version you downloaded is for 64-bit platforms and the error says it couldn't load something for a 32-bit platform.)

**Comment by MindeKing** [comment]
After extracting the .zip and double-clicking the .jar, right-clicking and **O̲pen**ing the .jar, once again, nothing is happening.
Doesn't even look like anything's running in the background using Task Manager.
I tried using the console again, and it would appear that I've received the same exact error message again.
![image](https://user-images.githubusercontent.com/26449194/202327747-7e37a216-12aa-4eb4-a5a2-7ba89d6edda2.png)

At least it make sense that this one wouldn't run, since my computer does appear to be a 64-bit platform.
![image](https://user-images.githubusercontent.com/26449194/202326818-6eb4af11-80de-4e76-88a7-cf31d57381c1.png)

Appreciate the help though.

**Comment by MindeKing** [comment]
After extracting the .zip and double-clicking the .jar, right-clicking and **O̲pen**ing the .jar, once again, nothing is happening.
Doesn't even look like anything's running in the background using Task Manager.
I tried using the console again, and it would appear that I've received the same exact error message again.
![pokepain 32](https://user-images.githubusercontent.com/26449194/202328382-36663d1e-e008-46ed-907f-0183bad49872.png)

At least it make sense that this one wouldn't run, since my computer does appear to be a 64-bit platform.
![image](https://user-images.githubusercontent.com/26449194/202328373-629c5fa9-4d9a-40cc-bb5a-bbc0aab1206b.png)

Appreciate the help though.

I will take the README's advice though and download the Java thing they link to for Windows (Java SE Development Kit 17.0.5). Update to come soon, I suppose.

**Comment by MindeKing** [comment]
Unfortunately, after installing the aforementioned JDK,
(![image](https://user-images.githubusercontent.com/26449194/202331338-cc52201d-748f-4203-9a8e-354138f0f835.png))
neither the 32-bit or 64-bit Windows versions of the program seem to be working.
Attempting to run pokewilds.exe or pokewilds-compat.exe still produces the "Failed to launch JVM" window.
Attempting to run the .jar in either version from the console still produces a near-identical error message, only replacing "gdx.dll" with "gdx64.dll" and "32-bit" with "64-bit".

**Comment by fourlastor** [comment]
@MindeKing I'm not sure why this would happen, could you try doing this:

1. Open the pokewilds.jar file with an archive manager (like winzip, winrar, 7zip), you should see a list of files.
2. Copy the `gdx.dll` and `gdx64.dll` files from within the archive next to the game exe file
3. Run the game again

![image](https://user-images.githubusercontent.com/1263058/210207544-47853510-34c7-4263-864e-7793fa559f83.png)

**Comment by fourlastor** [comment]
https://github.com/libgdx/libgdx/issues/5524 this could be a possible cause of the issue, if your username contains non-ascii characters

**Comment by fourlastor** [comment]
There might be a workaround (original [post](https://steamcommunity.com/app/646570/discussions/1/2561864094351818098/)):

Create a new shortcut next to your pokewilds.exe file (download the windows version), and insert the following as the location:

`C:\Windows\System32\cmd.exe /c "SET USERNAME=ASCII && START /D ^"C:\Users\Full\Path\To\Pokewilds^" pokewilds.exe"`

change `C:\Users\Full\Path\To\Pokewilds` to the actual path to the pokewilds folder on your computer (the folder containing `pokewilds.exe`)

**Comment by MindeKing** [comment]
My sincerest apologies!
I did not comb through the documentation as well as I should have when I made the initial report, and I missed the section which states the game will not launch if there is an exclamation mark in the file directory.
I moved the installation to a different folder, and it works perfectly fine, even without any Java installed.
Thank you for all of your help and for working on this game in the first place!
![I am very extremely sorry](https://user-images.githubusercontent.com/26449194/210282006-dcc95086-9f4f-4ff5-bf9f-9c6d8e6d9f92.gif)

**Comment by fourlastor** [comment]
No problem! I'm glad to hear you managed to run the game :smile:

**Comment by tommyettinger** [comment]
I'm glad to say that this bug report finally got me to get up and work on a known bug in other cases, often affecting other games than this one. I think I have a good solution now that should get any games/apps that use LWJGL3 to work for users with non-A-to-Z letters in their usernames, a problem that's been around for years. It might even be as simple as a single .bat file that can be included next to a .jar file in case the JAR doesn't work...
