### ISSUE TITLE
performance issue in linux 64 bit

### ISSUE THREAD

**Issue by 4cex100** [SheerSt/pokewilds#308]
1. Performance issues in linux64(parrot os) moves like sleep powder,stunspore night shade etc
2. If accidentally opened 2 windows of pokewilds it would crash and restart the pc
3. Need optimization
4. need a version for android

**Comment by fourlastor** [comment]
> Performance issues in linux64(parrot os) moves like sleep powder,stunspore night shade etc

Could you elaborate?

> If accidentally opened 2 windows of pokewilds it would crash and restart the pc

The whole PC? I'm not sure what's going on

> Need optimization

This is always true : ) 0.8 is at its end of life however and won't likely receive more updates in this regard.

> need a version for android

This is planned, it won't be anytime soon though
