### ISSUE TITLE
No fullscreen option anywhere.

### ISSUE THREAD

**Issue by QINGKn** [SheerSt/pokewilds#314]
I am currently playing this game on my PC (windows). At the moment we are only able to maximize the window the game is running in. This is the first thing that bothers me, I hate it when I have that stupid bar above my game.

Now I wanted to play this game on my steamdeck. Its running fine trough Wine-windows emulator, but I am running the game is "gaming mode" so there is not even a possibility for me to click the maximize button because it does not exist in this view. This leave me with an mini screen with an extreme black border. If the game had any button shortcut or some ingame menu with an "full screen" option. This game would be so much more enjoyable and I would be able the take it anywhere.
Thanks in andvance.

**Comment by HaseoWeasel** [comment]
Steam deck In desktop mode with game open, right click on the top border or alt+f3 go to more actions, then click "Configure Special Application Settings" then at the bottom left u'll see "+ Add Property" click on that then search for fullscreen, then in the drop down click "Force" then click apply. Now the game will always launch in fullscreen, however when in game mode it will be a DS bottom size screen, unlink the desktop where it will be true full screen.

**Comment by QINGKn** [comment]
yeah, This is something I already did and like you suggested yourself it did not solve my problem. That why I posted this comment. So I don't really understand why you answered this comment? To tell me the problem I am experiencing is a real thing?

**Comment by willyuewu** [comment]
Just found this thread that gives a very elegant solution:
https://www.reddit.com/r/PokeWilds/comments/yz6onl/pokewilds_on_steam_deck_getting_fullscreen_in/?utm_source=share&utm_medium=web2x&context=3

works nicely for me.

**Comment by HaseoWeasel** [comment]
You don't need to be a dick, I was offering you advice, how was I suppose to know you already tried that not everyone knows how to use Linux, it's not like you said that you tried what I posted

**Comment by QINGKn** [comment]
@willyuewu Thanks a lot this works great
👍🏻👍🏻

**Comment by QINGKn** [comment]
@HaseoWeasel sorry was frustrated that nothing was working 😅

**Comment by QINGKn** [comment]
But the solution is available via this link: https://www.reddit.com/r/PokeWilds/comments/yz6onl/pokewilds_on_steam_deck_getting_fullscreen_in/?utm_source=share&utm_medium=web2x&context=3

**Comment by HaseoWeasel** [comment]
Yeah no-problem glad the post that willyuewu posted helped I'm going to have to do it when I get around to it and put the game back on my deck

**Comment by HaseoWeasel** [comment]
@QINGKn No-problem glad the post that willyuewu posted helped I'm going to have to do it when I get around to it and put the game back on my deck
