### ISSUE TITLE
Can only walk up

### ISSUE THREAD

**Issue by benwormz** [SheerSt/pokewilds#315]
Once I open the game generator the up arrow is constantly being pressed. If I generate the game the sprite immediately starts walking up, and I can't turn or stop in any way.

**Comment by Codebender0** [comment]
having a similar issue, got stuck walking upward while in the egg hatch animation.

**Comment by Codebender0** [comment]
Additional testing shows:
On the main menu, the up arrow and left arrow does not work.

**Comment by HuangLiPang** [comment]
Same issue

**Comment by fourlastor** [comment]
Did you by any chance change the bindings in the `settings.txt` file? What system are you running on?

**Comment by Codebender0** [comment]
> 

ah, sorry about that
Turns out something heavy ended sitting on another input peripheral and that locked me to only going up.

**Comment by fourlastor** [comment]
Oh, glad to hear you solved!
