### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by Catwah** [SheerSt/pokewilds#331]
[error.log](https://github.com/SheerSt/pokewilds/files/10086761/error.log)

When I try to run the game, it won't open/can't create window :( Details attached.

**Comment by Catwah** [comment]
Okay, I had a look at some previous posts and found the solution, courtesy of the user, fourlastor.  Posting here in case anyone else comes across this issue:

This error usually indicates that your graphics card driver doesn't support something. You can try two things:

Try to update the graphics card drivers, they might be outdated. This is preferrable as the game (and your computer overall) will run better with updated drivers.
Follow the following instructions to run it in compatibility mode (this will run most of the times, but it might be slower):
How to start the game in compatibility mode (Windows 7/10):
Open the folder containing pokewilds.exe
Shift + right-click in an empty space in the folder and select 'Open powershell window here' (this will be 'Open command window here' in Windows 7)
Type cmd in the window and press enter. (skip this in Windows 7)
Type pokewilds.exe angle_gles20 into the window and press enter.

**Comment by fourlastor** [comment]
@Catwah sorry for the late reply and glad you found the solution! closing this as resolved
