### ISSUE TITLE
Suggestion to easy packing the game for macOS

### ISSUE THREAD

**Issue by lucasliet** [SheerSt/pokewilds#332]
you could use https://github.com/tofi86/universalJavaApplicationStub to pack any java application to look like a native macOs application

here is a exemple a did for myself

https://www.mediafire.com/file/665dr0guhx5desa/PokeWilds_v0.8.7.zip/file

![image](https://user-images.githubusercontent.com/49222261/203879189-32bfaafb-a7af-4e49-89d2-6bd40b66a524.png)
![image](https://user-images.githubusercontent.com/49222261/203879247-20d12a10-3053-42bf-b944-0761dd414e03.png)

thats the app i've used to convert the icon to .icns format
https://github.com/onmyway133/IconGenerator

but here is the icon i've converted
[AppIcon.icns.zip](https://github.com/SheerSt/pokewilds/files/10087903/AppIcon.icns.zip)

of course users could just copy any image and paste on mac's folder settings to set any custom icon too

**Comment by danieltaylor** [comment]
Would you mind sharing the command/variables you used to generate the app?

Also, I remade the icon to match the standard macOS icon shape if anyone is interested in using it:
[AppIcon.icns.zip](https://github.com/SheerSt/pokewilds/files/10330473/AppIcon.icns.zip)

**Comment by fourlastor** [comment]
Hi @lucasliet thank you for your suggestion, we have a stub for packing pokewilds with mac directly when building already, it's just still in progress (mostly due to other things getting higher priority).

Having control on the build system, we don't need external apps, as [jlink](https://docs.oracle.com/javase/9/tools/jlink.htm) + a custom app folder can do this

**Comment by lucasliet** [comment]
@danieltaylor 
> Would you mind sharing the command/variables you used to generate the app?
> 
> Also, I remade the icon to match the standard macOS icon shape if anyone is interested in using it: [AppIcon.icns.zip](https://github.com/SheerSt/pokewilds/files/10330473/AppIcon.icns.zip)

I haven't generated the app, just downloaded the "otherplatforms" one from the release page
https://github.com/SheerSt/pokewilds/releases/download/v0.8.8/pokewilds-otherplatforms.zip

---

@fourlastor 
> Hi @lucasliet thank you for your suggestion, we have a stub for packing pokewilds with mac directly when building already, it's just still in progress (mostly due to other things getting higher priority).
> 
> Having control on the build system, we don't need external apps, as [jlink](https://docs.oracle.com/javase/9/tools/jlink.htm) + a custom app folder can do this

That's great news! I'm looking foward for that feature, thanks for reply

**Comment by lucasliet** [comment]
@fourlastor that mac release has been discarded?

**Comment by fourlastor** [comment]
@lucasliet we're rewriting the game in Godot :) that will sort also the mac packaging
