### ISSUE TITLE
Once I start trying to plant then I can't stop planting

### ISSUE THREAD

**Issue by cloa513** [SheerSt/pokewilds#337]
I use the item of an apricorn seed then it is stuck in the planting mode until I use up all the seeds. It won't stop.

**Comment by Arthuriing** [comment]
hold X

**Comment by cloa513** [comment]
Thanks for your reply why couldn't it just be press X

**Comment by fourlastor** [comment]
> why couldn't it just be press X

This would be conflicting with the run command
