### ISSUE TITLE
The Ultimate Pokémon Asset Archive

### ISSUE THREAD

**Issue by Quizer9O8** [SheerSt/pokewilds#344]
A person by the name Lewtwo ([@Lewchube](https://twitter.com/Lewchube) on Twitter) has created a high quality Pokémon visual resource assets database for artists, content creators and fans of the series! PokéWilds or anyone else could really benefit using these assets for future projects. For anyone interested here's a link to the asset archive:
https://drive.google.com/drive/folders/16bSaqcst0tOMsz4rGBzPK_iZvgx4DZJX

**Comment by fourlastor** [comment]
@Quizer9O8 this looks great! However we have internal contributors that have made an amazing job at creating original sprites, and we will be using these in future versions (0.9.x and later)
