### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by Soundtoxin** [SheerSt/pokewilds#350]
Hello, I just came across this repository and noticed there is no LICENSE or COPYING file, making your project default to All Rights Reserved. Since you're sharing it publicly, that may not have been your intention. If you need help picking a license, this website may be useful:

https://choosealicense.com/

**Comment by fourlastor** [comment]
Hi! This repo is just a public facing one to be able to host the releases :) the code is private, that's why there isn't a license file
