### ISSUE TITLE
Improved build menu.

### ISSUE THREAD

**Issue by JLEADO** [SheerSt/pokewilds#351]
While the building system is great, I feel that it could use a few quality of life additions to help realize its maximum potential, from my experience with the game so far the biggest improvement would be some sort of build menu so you can more easily find what you are looking for. I included a mock up of what I think would be a good solution, but feel free to add your own ideas!

-JLeado
![pokeconcept](https://user-images.githubusercontent.com/114968680/205473393-3fa3233f-7d77-47c6-9885-519ed56eddec.png)

**Comment by fourlastor** [comment]
Hi @JLEADO, thank you for reporting this. A revamp of the UI is indeed planned with very much needed quality of life improvements such as this. I'll close the issue as we have a UI style that we're working on which will include all these bits
