### ISSUE TITLE
File

### ISSUE THREAD

**Issue by RandomizerGamerRIPLinky** [SheerSt/pokewilds#352]
Where's the shiny rates at? Just curious, since I wanted to see what the odds were on here.

**Comment by JENOVAAbsolute** [comment]
> Where's the shiny rates at? Just curious, since I wanted to see what the odds were on here.

1 in 256. This value will be adjustable when 0.9.0 releases.

**Comment by RandomizerGamerRIPLinky** [comment]
> > Where's the shiny rates at? Just curious, since I wanted to see what the odds were on here.
> 
> 1 in 256. This value will be adjustable when 0.9.0 releases.

Awesome! Thank you!!

**Comment by fourlastor** [comment]
Closing as it's been answered
