### ISSUE TITLE
Seismic Toss not super effective against dark types

### ISSUE THREAD

**Issue by Stanley-Zhu** [SheerSt/pokewilds#354]
Used seismic toss on an absol and only did 1x damage when it should be 2x since seismic toss is a fighting type move and absol is a dark type.

**Comment by Stanley-Zhu** [comment]
Seems to be an issue with the typing seismic toss has been coded to have. Isn't super effective against normal types either.

**Comment by KinktendoShamecube** [comment]
Seismic toss deals a set amount of damage that isn’t affected by type
effectiveness. The only thing that affects it is type immunity, which would
make ghost types immune to it.
