### ISSUE TITLE
Developer Application

### ISSUE THREAD

**Issue by Nexather** [SheerSt/pokewilds#356]
Hello, I am a professional software developer who has some experience in the MIPS assembly language. This project is very interesting to me and if the team is welcoming any new devs at the moment I'd be happy to join. I saw a user submitted an issue regarding Dig not working properly when a pokemon fainted and I thought it was a good example of what I could work on: https://github.com/SheerSt/pokewilds/issues/345

Please reach me at Nexather#6709 on discord if the team is interested!

**Comment by fourlastor** [comment]
Got in touch with the dev
