### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by Bird-South** [SheerSt/pokewilds#370]
Hello, I'm interested in game translation. Is there a translation method for this game?

**Comment by Lucasmaia435** [comment]
You can have a look at https://github.com/SheerSt/pokewilds/tree/main/i18n

**Comment by Bird-South** [comment]
Thank you for your answer. However, I have some problems after discussing with my friends. Do we only need to translate the files in i18n? Is there any text that needs to be decompiled to get it?

**Comment by fourlastor** [comment]
@Bird-South there isn't translation support for the game yet (versions 0.8.x), it will be added in a future version.

https://github.com/SheerSt/pokewilds/tree/main/i18n unfortunately isn't really used

**Comment by QCXYZ** [comment]
Hi, we are translating this game, 8 by 8 is actually quite uncomfortable, can you make it 10 by 10 or bigger

**Comment by fourlastor** [comment]
@QCXYZ what do you mean?

**Comment by QCXYZ** [comment]
> @QCXYZ什么意思？

Single letter size

**Comment by fourlastor** [comment]
I see. I'm not sure it's a good idea to start translating the game without coordinating with us.. We're revamping the ui completely so you risk wasting your time and having to throw the translations away.

I'd suggest waiting till the new version comes out as we're not adding new features to the current one (0.8.x)

**Comment by QCXYZ** [comment]
ok，thank you
