### ISSUE TITLE
[Bug]: Unable to allocate 2048000 bytes lds-v0.......

### ISSUE THREAD

**Issue by ZelDeMo9** [SheerSt/pokewilds#372]
### Game Version

v0.8.8

### Platform

Win10 64bit

### What happened?

I was battling with a pokemon , then the game crushed . I copy the bug report :
PokeWilds crashed :( reason:
(E)>
java.lang.OutOfMemoryError: Unable to allocate 2048000 bytes
lds-v0. com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:172)
lds.exe com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher,java:30)
lds-win Caused by: Unable to allocate 2048000 bytes
java.base/jdk.internal.misc.Unsafe.allocateMemory(Unknown Source)
java baseljava.nio.DirectByteBuffer.<init>(Unknown Source)
java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
org.lwjgl.BufferUtils.createByteBuffer(BufferUtils.java:75)
com.badlogic.gdx.backends.lwjgl3.audio.OgglnputStream.cinit>(OgglnputStream.java:111)
com.badlogic.gdx.barkends.lwjgl3.audio.Ogg$Music.read(Ogg.java:39)
com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.fill(OpenALMusic.java:256)
com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.play(OpenALMusic.java:94)
com.pkmngen.game.PlayMusic.step(Action.java:3687)
com.pkmngen.game.Game.render(Game.java:1316)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
com.badlogic.gdx backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:30)
Please report this issue on the PokeWilds discord or Github, and attach E:IPC gamelpokewilds0.8.8lpokewilds-v0.8.8-windows-64lerror.log to the bug report.

**Comment by ZelDeMo9** [comment]
Your game is really good , I love it. Please insist !

**Comment by fourlastor** [comment]
@ZelDeMo9 unfortunately the error means that pokewilds ran out of usable memory and couldn't continue to run anymore

The game still has a lot to improve in resources consumption, if your computer has less than ~4gb of ram, it might have some issues running islands bigger than S/M

**Comment by ZelDeMo9** [comment]
> 

ok ， I got it. Thank you for reply !

**Comment by fourlastor** [comment]
No problem!
