### ISSUE TITLE
l2$� (invalid encoding)

### ISSUE THREAD

**Issue by Ninja17** [SheerSt/pokewilds#376]
Running Ubuntu 14.04  X64, and when running the "pokewilds-x64" it returns no errors or launch and a new item is created in the folder called "l2$� (invalid encoding)"
I have java installed and verified that the app is set for "allow executing file as program" 
when putting this into terminal it returns:
/pokewilds-v0.8.8-linux-64/PokeWilds-x64: cannot execute binary file: Exec format error

I have also confirmed i am "Running the newest version" when running "sudo apt install libfuse2 -y"

Next i tried the "other platforms" version and am unable to launch that aswell
Error: Unable to access jarfile pokewilds.jar
even though its in the exact same folder? (permissions are set to default and/or Read+Write)

Hope there is an easy fix for this im missing? 
Thanks!

**Comment by Derailedzack** [comment]
What architecture are you using?

**Comment by Ninja17** [comment]
Jetson TK1 ARM Running Ubuntu.. Figured it wouldn't run on this =/ but if
you have an arm version coming for Android it may work 😁

**Comment by fourlastor** [comment]
@Ninja17 sorry for the late answer, pokewilds runs on arm but not the Linux version, you need to use the other platforms version and install java, then follow the readme instructions on how to make a launcher
