### ISSUE TITLE
[Bug]: Window couldn't be create

### ISSUE THREAD

**Issue by Hare-kushi** [SheerSt/pokewilds#400]
### Game Version

v0.8.8

### Platform

Windows 10

### What happened?

2023-02-07T17:59:55.2633503+01:00 Couldn't create window

com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
com.pkmngen.game.desktop.DesktopLauncher.main(DesktopLauncher.java:30)

**Comment by DayBreakShifter** [comment]
Try running pokewilds-compat.exe.

**Comment by Pongadeedle-1** [comment]
try place it on a wall

**Comment by fourlastor** [comment]
This should be solved using pokewilds compat as suggested
