### ISSUE TITLE
[Feature Request]: Add build/compilation instructions

### ISSUE THREAD

**Issue by hifinerd** [SheerSt/pokewilds#408]
### What would you like to request?

I cannot seem to find a makefile or any kind of tool to allow for compilation, and for others, some might just prefer to compile software themselves, so I would like to request the inclusion of compilation instructions.

**Comment by fourlastor** [comment]
This isn't the game repo, it's just a repository with the assets and the releases, the game repo is closed source

**Comment by DiamantTh** [comment]
Is the publication of the source code planned?
Otherwise it makes no sense to offer this on github

**Comment by fourlastor** [comment]
It isn't. Github is great as a hosting platform for the releases and to automate the release process via actions (which we do in the code repository)
