### ISSUE TITLE
[Bug]: All interaction and battle text becomes unknown font.

### ISSUE THREAD

**Issue by TacoRabbit** [SheerSt/pokewilds#420]
### Game Version

v0.8.9

### Platform

Windows 10 64Bit

### What happened?

I had interacted with a sign that had unknown text, the music had changed and upon interacting with anything else the text becomes unknown font for both battles and interactions. After a battle ends, it returns to normal.
![image 2](https://user-images.githubusercontent.com/75909881/233806379-7d6dc935-13f1-4449-a947-baac12bccdac.png)
![image](https://user-images.githubusercontent.com/75909881/233806188-150dfc0a-07fb-45e3-90ba-a77946e08603.png)
![2023-04-22 13_54_29-Window](https://user-images.githubusercontent.com/75909881/233806231-39ba7c08-42e2-4295-a70c-5ba0a4a9c89b.png)

**Comment by lukasz4444** [comment]
**Close it.** 
@TacoRabbit 
**This is not a glitch** just go to the **grass and encounter an unown.**
