### ISSUE TITLE
[Feature Request]: ESP Language

### ISSUE THREAD

**Issue by Litch-Kurayami** [SheerSt/pokewilds#422]
### What would you like to request?

Dear development team,

I am writing to express my interest in your Pokémon game and respectfully request that you consider adding the Spanish language as an option in your English game.

As you may have noticed, there is a large Spanish-speaking community around the world, and many of us are Pokémon video game enthusiasts. By adding the Spanish language to your game, you would not only be expanding your player base, but also providing a more inclusive experience for those who speak Spanish as their primary or secondary language.

I understand that adding a new language may take time and resources, but I hope that you can seriously consider this request and see the value it would add to the game. If possible, I would love to know if you have already considered this option and if there are any plans to implement the Spanish language in the future.

Thank you in advance for your attention to this request, and I look forward to your response.

Sincerely,
Litch-Kurayami

**Comment by fourlastor** [comment]
Hi, we are planning on adding translations to the next major release of the game (0.9), it's still in development but it will have the language options!
