### ISSUE TITLE
[Feature Request]: License

### ISSUE THREAD

**Issue by Azeved00** [SheerSt/pokewilds#439]
### What would you like to request?

Hello,

I use [NixOS](https://nixos.org/) as my main operating system and I wanted to create a derivation (package) for this game.
For that i need to license which this repo does not have.

I was wondering if it was possible to add a license or at least get permission to add this application to NixOS package repo.

Thank you for this amazing game!

**Comment by fourlastor** [comment]
Unfortunately I don't think we can allow that, as it's not 100% clear on how much ourselves are allowed to let other people redistribute pokewilds, so we decided to avoid stores/repositories entries
