### ISSUE TITLE
Is there any list of all Pokémon available in the game?

### ISSUE THREAD

**Issue by Lagartooo** [SheerSt/pokewilds#44]
Hey! Loving the game so far! I was wondering if there's any list containing every Pokémon in the game! I didn't see any hoenn starters yet and I wanted to know if they're in the game :D

**Comment by SheerSt** [comment]
Hi there @Lagartooo - there is a google sheet that should contain that info: https://docs.google.com/spreadsheets/d/1b6tkjKaDcFCYxvhWDHQi2B18lhtqgueFNNOP8ZdtTLs

**Comment by fourlastor** [comment]
Closing this as resolved
