### ISSUE TITLE
[Feature Request]: Port for RG35xx

### ISSUE THREAD

**Issue by johnsledget** [SheerSt/pokewilds#443]
### What would you like to request?

Is this possible to port this amazing game to RG35xx? I tried but i failed. See images for example.
I used the build under other platform, pokewilds.jar. 
Lastly, i was able to use higher glibc and the result was segmentation fault. From there i dont know what to do. Please have comments and advice.

Ran under koriki os.
![IMG_20231026_222738](https://github.com/SheerSt/pokewilds/assets/24409214/92d51525-d654-4c68-b7d7-1cf1f60bedf2)

Ran under garlic os.
![IMG_20231026_223042](https://github.com/SheerSt/pokewilds/assets/24409214/dfa5a8f9-9b16-4acd-9b72-a4aef0e89313)

**Comment by fourlastor** [comment]
Unfortunately, this is not possible, I had a chat in the Anbernic discord a year and something ago about it.

Pokewilds is made with [libgdx](https://libgdx.com/), which is made with [LWJGL](https://www.lwjgl.org/), which [doesn't run](https://discourse.glfw.org/t/glfw-with-lwjgl-on-anbernic-rg351p-with-rk3326-on-batocera/2363) on the platform. The main issue seems to be the lack of a window system that LWJGL supports (x11/wayland).
