### ISSUE TITLE
Allow B button for going through dialog

### ISSUE THREAD

**Issue by lesleyrs** [SheerSt/pokewilds#49]
It would be great if spamming B would let you go through all dialog just like how it works in the original games, besides from the initial dialog start so that way you can't re-start it when you don't intend to.

Changed issue as the last thing didn't end up being a problem.

**Comment by return2monki** [comment]
Never mind, I was able to jump off after stepping off ponyta first. But the B button thing applies still.

**Comment by DizzyDJW** [comment]
This would be especially useful for encounters with aggressive pokemon. Don't want to agitate them again while going through the text.

Along with this please give us options for faster text speed or even better, speedhack. Allow us to make the game go up to like 8x faster if possible.

**Comment by fourlastor** [comment]
Speedhacks aren't planned.

For the B button, I'll report this to the team, but it won't be a something for the current version (we're focusing on fixing issues and improving performances)

For the text speed, you should be able to change it by changing this line in the `settings.txt` file:
```
textSpeed=mid
```
You can change this to `textSpeed=slow`, `textSpeed=fast` or `textSpeed=inst`

Closing the issue in the meantime as we're moving it to be tracked internally
