### ISSUE TITLE
where's the rest of the source code?

### ISSUE THREAD

**Issue by cklapperich3** [SheerSt/pokewilds#51]
I was hoping to mess around with the code, make my own branch, and maybe try adding new features. 

It says the project is written in java but I only see assets and a little bit of asm? am I missing something?

**Comment by fourlastor** [comment]
Hi! The source code is private :slightly_smiling_face: this repository is to hold the various releases

**Comment by TaraSophieDev** [comment]
Kinda sad, tho understand if it's private, but would like to know why that is. Would've loved to fork it and make an android build for it.

**Comment by fourlastor** [comment]
The android build is already in the works!

The code is private as unfortunately some parties might make issues if it wasn't

**Comment by TaraSophieDev** [comment]
Totally understandable. If I can help in others way email me.

**Comment by FloMaskine** [comment]
> The android build is already in the works!
> 
> The code is private as unfortunately some parties might make issues if it wasn't

Any news on this?
