### ISSUE TITLE
[Request] Linux arm64 version

### ISSUE THREAD

**Issue by Azkali** [SheerSt/pokewilds#52]
Would it be possible to release arm64 versions of the game ?

Currently the only way to play this game on arm64 platforms would be through x86_64 emulation (Fex, Rosetta2, Box86/64) which can cause huge performance loss on some platforms (Tegra for example)

**Comment by zjuHong** [comment]
By the way, would it be possible to release versions of the game for mac m1?

**Comment by SheerSt** [comment]
@zjuHong I have been working the past couple of days on a build of v0.8.3 that is compatible with M1s 👍

**Comment by SheerSt** [comment]
@zjuHong @Azkali I have been working on a mac / M1 build recently and am looking for people to help me test it. If either of you are interested you will need to DM me (SheerSt) on the wilds discord server (I have a private channel on the server for all feedback and issues).

**Comment by Azkali** [comment]
I am not finding you on discord, can you give your full discord ID please (using th search bar didn't lead anywhere)
Otherwise you can find me azkali#1570

**Comment by SheerSt** [comment]
@Azkali here is the Wilds discord server - https://discord.gg/zzuVK8MdKK

Or if you'd like to skip all that, here is the latest mac build that I am testing - https://github.com/SheerSt/pokewilds-updater/releases/latest/download/pokemon-wilds-mac64.zip

**Comment by zjuHong** [comment]
@SheerSt I can't log in to the Wilds discord server, is there another way? And I have downloaded pokemon-wilds-mac-arm64.app.zip and pokemon-wilds-mac64.app.zip in v0.8.3-mac.5 and unziped to run them, but it doesn't work perfectly.

by the way, I can run pokemon-wilds-v0.8.3-mac.5.app/Contents/MacOS/pokemon-wilds in terminal, but it doesn't work in the GUI

for pokemon-wilds-v0.8.3-mac-arm64.5.app in terminal, the error code is as follow:  dlopen(pokemon-wilds-v0.8.3-mac-arm64.5.app/Contents/Resources/jre/lib/jli/libjli.dylib, 0x0001): tried: 'pokemon-wilds-v0.8.3-mac-arm64.5.app/Contents/Resources/jre/lib/jli/libjli.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

Are the two names reversed?

**Comment by fourlastor** [comment]
Hi, sorry for the long wait @zjuHong @Azkali, the latest [release](https://github.com/SheerSt/pokewilds/releases) should be compatible with Mac (download the `pokewilds-otherplatforms.zip` version), here are the instructions on how to run it:

Mac
 - Requires Java to be installed: https://www.oracle.com/java/technologies/downloads/#jdk17-mac
 - Single-click on the pokemon-wilds-v084-otherplatforms2 folder, click on Finder on the top bar, then Services, then select New Terminal at Folder. 
 - Enter `java -jar pokewilds.jar` into the terminal and press enter.

Right now it's a bit inconvenient to start, we're working on making this easier in the future!
