### ISSUE TITLE
Alolan Exeggcutor visual glitch

### ISSUE THREAD

**Issue by Testare** [SheerSt/pokewilds#55]
Love the game! It's nostalgic feel, yet novel gameplay... GF take notes!

Just wanted to report a small visual glitch with alolan exeggcutor when using cut. When the trainer sprite is behind him, it looks like the exeggcutor's neck goes right through his head lol.

![Screenshot_20220620_082241](https://user-images.githubusercontent.com/4080459/174634338-cd1cb156-96ef-4ab8-b469-91002fac4608.png)

**Comment by fourlastor** [comment]
Thank you for the report! I'm closing this issue as this is already tracked internally
