### ISSUE TITLE
Bug: Switching items with cancel field fucks up the menu

### ISSUE THREAD

**Issue by scheu1** [SheerSt/pokewilds#59]
By switching items (Enter/Start) with the cancel field, the item will be deleted and the cancel button multiplied.
Loading an old save state seems the only possibility to undo it.
![1](https://user-images.githubusercontent.com/108091360/175369597-8dd83342-0c36-4763-a680-bc4f3921073a.jpg)

**Comment by fourlastor** [comment]
Hi @scheu1! Thank you for the report and sorry for the late reply

This has been fixed in the [latest release](https://github.com/SheerSt/pokewilds/releases/latest)
