### ISSUE TITLE
just found this project and i am so interested!

### ISSUE THREAD

**Issue by GreenForzeGaming** [SheerSt/pokewilds#62]
is there any other place you can follow progress, like discord or something. gotta prep for the 0.9 version so i can play with friends!

**Comment by SheerSt** [comment]
@GreenForzeGaming hi there - yes there is a discord server at https://discord.gg/zzuVK8MdKK

**Comment by GreenForzeGaming** [comment]
@SheerSt is there a place i could help with? i love spriting and create overworld sprites, ive always wanted a good reason for it, and if i can support this it be a dream come true

**Comment by SheerSt** [comment]
@GreenForzeGaming I saw that you posted on the discord earlier, lmk if you need any more info in order to plug in with the community :)

**Comment by fourlastor** [comment]
Closing as resolved
