### ISSUE TITLE
Garbled Text involving regular text, unown and different tiles.

### ISSUE THREAD

**Issue by MozFox1** [SheerSt/pokewilds#63]
![B9C49447-593B-4415-8316-EA080F11E360](https://user-images.githubusercontent.com/107306154/176151012-07621a79-2025-435d-be3d-7f7e606225c4.jpeg)
This also happens to text on Pokémon interactions, storage box text and signs.

**Comment by SheerSt** [comment]
@MozFox1 hi there - it's actually an in-game event and it's supposed to work like that. Most people also think it's a bug. I am planning to change how the event works in the future so that it's more clear that it's not a bug.

**Comment by MozFox1** [comment]
Is it also a feature to garble up Storage Screens and PlayerPlaced Signs and Graves?

**Comment by SheerSt** [comment]
@MozFox1 yes, it will garble text anytime there is a textbox 'pop up'

**Comment by luckydog79** [comment]
I kind of like it this way

**Comment by fourlastor** [comment]
Closing as resolved
