### ISSUE TITLE
bugs and flying types dont seems to be dropping the items

### ISSUE THREAD

**Issue by carrotee123** [SheerSt/pokewilds#64]
ive fainted about 20 or so of flying types and bug types but they wont drop the items am i doing something wrong

**Comment by SheerSt** [comment]
@carrotee123 hi there - pokemon will generate items if they are standing in their habitat (not in battle). There's more info on the google sheet - https://docs.google.com/spreadsheets/d/1b6tkjKaDcFCYxvhWDHQi2B18lhtqgueFNNOP8ZdtTLs

**Comment by carrotee123** [comment]
oh whoops
