### ISSUE TITLE
Pokemon don't learn some moves

### ISSUE THREAD

**Issue by CondorLu** [SheerSt/pokewilds#66]
Hi! I've seen that some Pokemon (like Gastly's evolution line and Squirtle's one) do not learn some moves. Is there a way to fix this problem?

**Comment by Enzi-Sloh** [comment]
They don't have every move in the game yet because they need to build the sprite animations for them so sadly we'll just have to wait. You can always check the excel sheet to see if they need any sprites if you want to help make them.

**Comment by fourlastor** [comment]
Closing as this work is planned
