### ISSUE TITLE
Mac Launcher bug

### ISSUE THREAD

**Issue by GCdye** [SheerSt/pokewilds#79]
Java window opens and immediately crashes. Any help would be amazing

**Comment by ElijahL1nk** [comment]
I'm having this same issue! I'm trying to figure it out but if you or anyone else finds any useful info please lmk

**Comment by SheerSt** [comment]
@GCdye @ElijahL1nk would you be willing to try this out?

"""
Single-click on the `Contents/Resources` folder, click on Finder, then Services, then select New Terminal at Folder. Enter `sudo java -jar pokewilds.jar` into the terminal, type in your user password when prompted, and press enter.
"""

If that doesn't work, there is a newer mac version that is currently undergoing testing. It will have bugs but it should fix the issue you're both having. I would be happy to add either of you, you'll need to DM me on the pokewilds discord server for access.

**Comment by ElijahL1nk** [comment]
Okay yeah, i tried it out but it didn't really work. incase its helpful info for you to know, after I put in the code and my password it just returns "Unable to access jarfile".

and I will try to join the discord rn ill let you know.

**Comment by washburnello** [comment]
This worked for me @ElijahL1nk.

1. Followed instructions from @SheerSt but before typing in the command
2. cd Contents/Resources
3. java -jar pokewilds.jar

**Comment by Charizardbozz** [comment]
> @GCdye @ElijahL1nk would you be willing to try this out?
> 
> """ Single-click on the `Contents/Resources` folder, click on Finder, then Services, then select New Terminal at Folder. Enter `sudo java -jar pokemon-wilds.jar` into the terminal, type in your user password when prompted, and press enter. """
> 
> If that doesn't work, there is a newer mac version that is currently undergoing testing. It will have bugs but it should fix the issue you're both having. I would be happy to add either of you, you'll need to DM me on the pokewilds discord server for access.

**Comment by Charizardbozz** [comment]
im running 11.6.7 software and my computer wont update more because it isn't compatible can i still use this version?

**Comment by Maartz** [comment]
Running on M1 Max, macOS Ventura with Java 22.
To manage more easily which JDK is installed, I recommend you to use [sdkman](https://sdkman.io). It's pretty useful.
Great job, it works very well!

**Comment by fourlastor** [comment]
@Maartz great suggestion, sdkman is really useful :+1: 

@Charizardbozz yes, usee sdkman to install java, and then follow the instructions :)

Closing the issue as resolved
