### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by BacoF54T5** [SheerSt/pokewilds#84]
i am using the Linux install, i have java installed and i had the game running but i tried running it again and the linux portal gave me this error
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
any clue what to do?

**Comment by fourlastor** [comment]
@BacoF54T5 could you try downloading the [latest release](https://github.com/SheerSt/pokewilds/releases/latest/)? The linux version includes an all-included executable that you should be able to just double click:  
![image](https://user-images.githubusercontent.com/1263058/193359967-4531cd80-36af-42f4-9a7b-08fc90c50f38.png)
