### ISSUE TITLE
window wont open

### ISSUE THREAD

**Issue by Bustednursox** [SheerSt/pokewilds#87]
so, after I extracted the files I tried starting the .exe and I get game sound, but no window pops up for the game and I also get a game icon on the task bar and ill click on it but still brings up no window so currently can't play but listen to game music

**Comment by fourlastor** [comment]
Hi! Sorry for the late reply, the [latest release](https://github.com/SheerSt/pokewilds/releases/latest) has changed a lot since (and works much better on all platforms), I'm closing this as outdated in the meantime
