### ISSUE TITLE
Unable to open macOS version

### ISSUE THREAD

**Issue by nnichols133** [SheerSt/pokewilds#93]
**Macbook Air M1 8c GPU**
MacOS version: Monterey 12.4
Java version: 1.0 (1.8.0_341)

After downloading and installing Java, i am unable to run the game. The game opens in a little black java window. Nothing happens for around 15 seconds, then the window closes
<img width="957" alt="Screen Shot 2022-07-26 at 4 59 26 PM" src="https://user-images.githubusercontent.com/44559819/181132424-e6f4686a-8feb-427a-8818-14f274ab6ea0.png">
.

**Comment by SheerSt** [comment]
@nnichols133 Can you try these instructions?

1. Unzip pokemon-wilds-mac64.zip and place folder in desired location (Applications folder is a good option)
2. Open Pokemon-wilds-v0.8.3-mac, open Contents
3. Single-click on the Resources folder, click on Finder on the top bar, then Services, then select New Terminal at Folder. 
4. Enter sudo java -jar pokemon-wilds.jar into the terminal, type in your user password when prompted, and press enter. 

If that doesn't work, please join the PokeWilds discord and I can give you access to a test mac build of the game.

**Comment by nnichols133** [comment]
@SheerSt, opening the game via terminal worked. Thanks!
