### ISSUE TITLE
Mac Launcher Busted

### ISSUE THREAD

**Issue by SenorBug** [SheerSt/pokewilds#95]
I noticed someone else had this issue and were able to get an experimental Mac version to use, hoping I could get that as well. Cannot launch the game from the java launcher and I have exhausted myself trying to troubleshoot it myself. How can I get this version?

**Comment by SheerSt** [comment]
@SenorBug Can you try these instructions?

- Unzip pokemon-wilds-mac64.zip and place folder in desired location (Applications folder is a good option)
- Open Pokemon-wilds-v0.8.3-mac, open Contents
- Single-click on the Resources folder, click on Finder on the top bar, then Services, then select New Terminal at Folder.
- Enter sudo java -jar pokemon-wilds.jar into the terminal, type in your user password when prompted, and press enter.

If that doesn't work, please join the PokeWilds discord and I can give you access to a test mac build of the game.

**Comment by SenorBug** [comment]
It worked! thank you! Can't wait to try out the game it looks great!

**Comment by fourlastor** [comment]
Closing as resolved
